services:
  app:
    container_name: ${APP_NAME}
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
      WAIT_BEFORE_HOSTS: 5
      WAIT_SLEEP_INTERVAL: 3
    networks:
      - go-gin-auth-api-starter-kit-stack

  postgres:
    container_name: ${DB_SERVER_NAME}
    image: postgres:15-alpine
    ports:
      - ${DB_EXPOSE_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - go-gin-auth-api-starter-kit-stack

volumes:
  database_postgres:

networks:
  go-gin-auth-api-starter-kit-stack:
    driver: bridge
